iso_path: "/zfs01/iso/template/iso"
isos:
  - name: "TrueNAS-SCALE-25.10.1.iso"
    url: "https://download.sys.truenas.net/TrueNAS-SCALE-Goldeye/25.10.0.1/TrueNAS-SCALE-25.10.0.1.iso"
    checksum: "6eb4e7c86c525d3ff705996139f1d823c01d8af15b13fef017bb5c20b3e39320"
    checksum_type: "sha256"
  - name: "OPNsense-25.1-dvd-amd64.iso"
    url: "https://mirrors.nycbug.org/pub/opnsense/releases/25.1/OPNsense-25.1-dvd-amd64.iso.bz2"
    checksum: "68efe0e5c20bd5fbe42918f000685ec10a1756126e37ca28f187b2ad7e5889ca"
    checksum_type: "sha256"
  - name: "OPNsense-25.7-dvd-amd64.iso"
    url: "https://mirrors.nycbug.org/pub/opnsense/releases/25.7/OPNsense-25.7-dvd-amd64.iso.bz2"
    checksum: "fa4b30df3f5fd7a2b1a1b2bdfaecfe02337ee42f77e2d0ae8a60753ea7eb153e"
    checksum_type: "sha256"
  - name: "ubuntu-24.04.3-live-server-amd64.iso"
    url: "https://releases.ubuntu.com/24.04.3/ubuntu-24.04.3-live-server-amd64.iso"
    checksum: "c3514bf0056180d09376462a7a1b4f213c1d6e8ea67fae5c25099c6fd3d8274b"
    checksum_type: "sha256"
  - name: "ubuntu-25.10-live-server-amd64.iso"
    url: "https://releases.ubuntu.com/25.10/ubuntu-25.10-live-server-amd64.iso"
    checksum: "dc54870e5261c0abad19f74b8146659d10e625971792bd42d7ecde820b60a1d0"
    checksum_type: "sha256"
